- README.md
> docs: menambahkan pengertian SQL

- SQL Intro/SQL_DB_Relational.md
- SQL Intro/SQL_Intro.md
> add:Lengkapi Penjelasan Introduction DB, DBMS DB relational

- Silabus.md
gimana om-om sekalian @nomadkode @mhaikalla hehehe
> add:silabus atau roadmap bellshade sql

- Data Manipulation Language/INSERT.md
@nomadkode @mhaikalla @agnes-diza-fahira hehehe
review nya dong, om, master, kakak !!
> add:insert into query

- 01_Pengenalan/4-SQL Comment.md
Review please @mhaikalla @agnes-diza-fahira @bellshade/docs-team 
Thank uu ><
> add:sql comment

- Basic/02_Data_Manipulation_Language/3_Mengupdate_Data/README.md
> feat: menambahkan query update

- Basic/02_Data_Manipulation_Language/2_Menginput_Data/README.md
- Basic/02_Data_Manipulation_Language/3_Mengupdate_Data/README.md
1. typo `nisd` -> `nish`
2. Menambah anotasi `NOT NULL` untuk mempertegas atribut `PRIMARY KEY`
> docs: mengubah contoh query

- Basic/02_Data_Manipulation_Language/1_Menampilkan_Data/README.md
> feat: menambah query menampilkan data

- README.md
Merapihkan readme pada repo SQL, dan membuat tabel materi yang ada pada SQL
> feat: memperbaiki readme dan menambahkan tabel materi SQL

- Basic/05_SQL_Operator/5_Aliasing/README.md
> feat:menambah materi alias

- Basic/05_SQL_Operator/6_Limit/README.md
> feat: menambahkan meteri limit

- Basic/06_Numeric_Functions/1_Math_Count/README.md
> feat: menambahkan meteri math count

- Basic/06_Numeric_Functions/2_Math_Average/README.md
Materi Average
- Menghitung rata-rata data di satu tabel
- Menghitung rata-rata data dengan kondisi
> feat: menambah materi average

- README.md
Ada beberapa tata bahasa dan penulisan yang saya perbaiki di README.md:
- Menambah _text alternative_ pada gambar agar lebih jelas.
- Memperbaiki typo penulisan.
- Pengubahan kalimat.
- Menghapus beberapa kata dan kata berulang.
Saya menggunakan:
- OS = Windows
- Markdown = GitHub
> docs: memperbaiki dokumentasi sesuai EYD

- Basic/06_Numeric_Functions/3_Math_MinMax/README.md
> feat: menambah materi math max min

- Basic/06_Numeric_Functions/4_Math_Sum/README.md
Materi Sum
- Menghitung hasil penjumlah suatu kolom
- Menghitung hasil penjumlah suatu kolom dengan kondisi
Issue
> feat: menambah materi math sum

- Basic/06_Numeric_Functions/2_Math_Average/README.md
Memperbaiki typo di contoh query
> fix: memperbaiki typo

- Basic/06_Numeric_Functions/5_Math_SQRT/README.md
Materi SQRT
- Menghitung akar kuadrat satu kolom
- Menghitung akar kuadrat satu data
Issue
> feat: menambah materi SQRT

- Basic/01_Pengenalan/1_Pengenalan_Database/README.md
- Basic/01_Pengenalan/2_Pengenalan_Database_Relational/README.md
- Basic/01_Pengenalan/3_Pengenalan_Query_Database/README.md
- Basic/01_Pengenalan/4_SQL_Comment/README.md
- Basic/02_Data_Manipulation_Language/1_Menampilkan_Data/README.md
- Basic/02_Data_Manipulation_Language/2_Menginput_Data/README.md
- Basic/02_Data_Manipulation_Language/3_Mengupdate_Data/README.md
- Basic/02_Data_Manipulation_Language/4_Menghapus_Data/README.md
- Basic/03_Data_Defintion_Language/1_Membuat_Object/README.md
- Basic/03_Data_Defintion_Language/2_Menampilkan_Object/README.md
- Basic/03_Data_Defintion_Language/3_Modifikasi_Object/README.md
- Basic/03_Data_Defintion_Language/4_Menghapus_Object/README.md
- Basic/03_Data_Defintion_Language/5_Menghilangkan_Data_Dalam_Object/README.md
- Basic/04_Data_Control_Language/1_Menerima_Akses/README.md
- Basic/04_Data_Control_Language/2_Menolak_Akses/README.md
- Basic/05_SQL_Operator/1_Operator_Aritmatika/README.md
- Basic/05_SQL_Operator/2_Operator_Perbandingan/README.md
- Basic/05_SQL_Operator/5_Aliasing/README.md
- Basic/05_SQL_Operator/6_Limit/README.md
- Basic/05_SQL_Operator/7_OrderBy/README.md
- Basic/05_SQL_Operator/8_Distinct/README.md
Seperti ini : 
Dibuat baru sampai materi 05_Operator
> docs: menambahkan navigasi next dan back pada materi setiap repo

- Basic/06_Numeric_Functions/6_Math_Round/README.md
Materi Round
1. Penjelasan
2. Sintak
3. Parameter
4. Contoh Query
Issue :
> feat: menambah materi math round

- Basic/05_SQL_Operator/9_UNION/README.md
> add: Menambah Materi UNION

- Basic/06_Numeric_Functions/8_Math_Floor/README.md
Materi Floor
1. Penjelasan
2. Sintak
3. Contoh Query
Issue :
> add: menambahkan materi math floor

- Basic/06_Numeric_Functions/9_Math_Random/README.md
Materi Random
1. Penjelasan
2. Sintak
3. Contoh Query
Issue :
> feat: menambah materi random

- Basic/10_Join_Table/2_Left_Join/README.md
Menambahkan Materi SQL yaitu LEFT JOIN pada bagian JOIN TABLE.
> feat: menambahkan materi SQL yaitu LEFT JOIN

- Basic/02_Data_Manipulation_Language/1_Menampilkan_Data/README.md
> add: penjelasan SQL SELECT DISTINCT

- README.md
Saya mengganti url untuk visitor badge karena url sebelumnya tidak bisa diaktifkan lagi.
> docs: memperbaiki visitor badge

- Basic/05_SQL_Operator/3_Operator_Logika/README.md
> feat: operator logika

- Basic/10_Join_Table/3_Right_Join/README.md
Menambah materi right join
- penjelasan right join
- contoh query right join
> feat: right join

- Basic/05_SQL_Operator/9_UNION/README.md
memperbaiki dokumentasi sql union untuk memudah dibaca dan di pahami.
> fix: memperbaiki dokumen materi.
